services:
  banco:
    image: mysql:lts
    container_name: container-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fastfood-db
    ports:
      - 3306:3306

  fastfood:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: container-fastfood
    ports:
      - 8080:8080
    depends_on:
      - banco
    restart: always